using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bcore.Utility
{
    public class ScpSystemConfigEnumCore
    {
        public static readonly string SYSTEM_THREADING_SLEEP = "SYSTEM_THREADING_SLEEP";
        public static readonly string CurrentVersion = "CurrentVersion";
        public static readonly string AF_SEND_NOTIFICATION = "AF_SEND_NOTIFICATION";
        public static readonly string EMAIL_SUPPORT = "EMAIL_SUPPORT";
        public static readonly string EMAIL_SUPPORT_TITLE = "EMAIL_SUPPORT_TITLE";
        public static readonly string LOGIN_NOTIFICATION_EMAILS = "LOGIN_NOTIFICATION_EMAILS";
        public static readonly string PURCHASE_NOTIFICATION_EMAILS = "PURCHASE_NOTIFICATION_EMAILS";
        public static readonly string ORDER_NOTIFICATION_EMAILS = "ORDER_NOTIFICATION_EMAILS";
        public static readonly string REFUND_NOTIFICATION_EMAILS = "REFUND_NOTIFICATION_EMAILS";
        public static readonly string CHARGEBACK_NOTIFICATION_EMAILS = "CHARGEBACK_NOTIFICATION_EMAILS";
        public static readonly string DEVELOPER_TEAM_EMAILS = "DEVELOPER_TEAM_EMAILS";
        public static readonly string MAINTENANCE_TEAM_EMAILS = "MAINTENANCE_TEAM_EMAILS";
        public static readonly string SYSTEM_ADMIN_NOTIFICATION_EMAILS = "SYSTEM_ADMIN_NOTIFICATION_EMAILS";
        public static readonly string SYSTEM_ADMIN_EMAILS = "SYSTEM_ADMIN_EMAILS";
        public static readonly string BCC_NOTIFICATION_EMAILS = "BCC_NOTIFICATION_EMAILS";
        public static readonly string EMAIL_SERVICE_HOST = "EMAIL_SERVICE_HOST";
        public static readonly string EMAIL_SERVICE_PORT = "EMAIL_SERVICE_PORT";
        public static readonly string EMAIL_SERVICE_USERNAME = "EMAIL_SERVICE_USERNAME";
        public static readonly string EMAIL_SERVICE_PASSWORD = "EMAIL_SERVICE_PASSWORD";
        public static readonly string EMAIL_RECEIVE_GIFTCODE = "EMAIL_RECEIVE_GIFTCODE";
        public static readonly string GOOGLE_ANALYTICS_ACCOUNT = "GOOGLE_ANALYTICS_ACCOUNT";
        public static readonly string GOOGLE_API_KEY = "GOOGLE_API_KEY";
        public static readonly string COMPANY_NAME = "COMPANY_NAME";
        public static readonly string PRODUCT_NAME = "PRODUCT_NAME";
        public static readonly string PRODUCT_NAME_ALIAS = "PRODUCT_NAME_ALIAS";
        public static readonly string PRODUCT_PREFIX_NAME = "PRODUCT_PREFIX_NAME";
        public static readonly string WEBSITE = "WEBSITE";
        public static readonly string WEBSITE_CPANEL = "WEBSITE_CPANEL";
        public static readonly string WEBSITE_ADMINTOOL = "WEBSITE_ADMINTOOL";
        public static readonly string WEBSITE_ANDROID_DOWNLOAD = "WEBSITE_ANDROID_DOWNLOAD";
        public static readonly string WEBSITE_IOS_DOWNLOAD = "WEBSITE_IOS_DOWNLOAD";
        public static readonly string WEBSITE_AFFILIATE = "WEBSITE_AFFILIATE";
        public static readonly string WEBSITE_SUPPORT = "WEBSITE_SUPPORT";
        public static readonly string WEBSITE_FORUM = "WEBSITE_FORUM";
        public static readonly string WEBSITE_BLOG = "WEBSITE_BLOG";
        public static readonly string WEBSITE_AMBIENT_VOICE_RECORDING_STREAMING = "WEBSITE_AMBIENT_VOICE_RECORDING_STREAMING";
        public static readonly string WEBSITE_PROTOCOL = "WEBSITE_PROTOCOL";
        public static readonly string LOGO_IMAGE_PATH = "LOGO_IMAGE_PATH";
        public static readonly string SHORTCUT_ICON_PATH = "SHORTCUT_ICON_PATH";
        public static readonly string LINK_HOW_TO_ADD_DEVICES_IOS = "LINK_HOW_TO_ADD_DEVICES_IOS";
        public static readonly string LINK_HOW_TO_ADD_DEVICES_ANDROID = "LINK_HOW_TO_ADD_DEVICES_ANDROID";
        public static readonly string LINK_TERMS_OF_USES = "LINK_TERMS_OF_USES";
        public static readonly string LINK_FAQ = "LINK_FAQ";
        public static readonly string LINK_CONTACT_US = "LINK_CONTACT_US";
        public static readonly string LINK_FORUM = "LINK_FORUM";
        public static readonly string LINK_BLOG = "LINK_BLOG";
        public static readonly string FOLDER_STYLE = "FOLDER_STYLE";
        public static readonly string CAPTCHA_ENABLE = "CAPTCHA_ENABLE";
        public static readonly string DISPLAY_MONITOR_APP_MESSAGE = "DISPLAY_MONITOR_APP_MESSAGE";
        public static readonly string DISPLAY_RENEW_OPTION = "DISPLAY_RENEW_OPTION";
        public static readonly string DISPLAY_COPYRIGHT = "DISPLAY_COPYRIGHT";
        public static readonly string DISPLAY_SET_LANG = "DISPLAY_SET_LANG";
        public static readonly string LANGUAGE_LIST = "LANGUAGE_LIST";
        public static readonly string LANGUAGE = "LANGUAGE";
        public static readonly string USER_REGISTRATION_PAGE_NICKNAME_NEEDS = "USER_REGISTRATION_PAGE_NICKNAME_NEEDS";
        public static readonly string USERNAME_MUST_BE_IN_EMAIL_FORMAT = "USERNAME_MUST_BE_IN_EMAIL_FORMAT";
        public static readonly string FEATURE_RESET_LOG_ENABLE = "FEATURE_RESET_LOG_ENABLE";
        public static readonly string FEATURE_DELIVERY_LOGS_BY_EMAIL_ENABLE = "FEATURE_DELIVERY_LOGS_BY_EMAIL_ENABLE";
        public static readonly string FEATURE_DISCOUNT_COUPONS_ENABLE = "FEATURE_DISCOUNT_COUPONS_ENABLE";
        public static readonly string FEATURE_DISCOUNT_COUPONS_PERCENT_WHEN_SEND_EMAIL = "FEATURE_DISCOUNT_COUPONS_PERCENT_WHEN_SEND_EMAIL";
        public static readonly string PAYPAL_SUPPORT_LITE_PACKAGE = "PAYPAL_SUPPORT_LITE_PACKAGE";
        public static readonly string AMBIENT_VOICE_RECORDING_AUDIO_PATH = "AMBIENT_VOICE_RECORDING_AUDIO_PATH";
        public static readonly string FREE_DAY = "FREE_DAY";
        public static readonly string DEFAULT_ACCESS_CODE = "DEFAULT_ACCESS_CODE";
        public static readonly string DEFAULT_PACKAGE_CODE = "DEFAULT_PACKAGE_CODE";
        public static readonly string USE_PROTOCOL_NAVIGATOR = "USE_PROTOCOL_NAVIGATOR";
        public static readonly string DISTRIBUTOR_DEFAULT_COMMISSION_PERCENT = "DISTRIBUTOR_DEFAULT_COMMISSION_PERCENT";
        public static readonly string ADMINTOOL_SHOW_PASSWORD = "ADMINTOOL_SHOW_PASSWORD";
        public static readonly string CDN_URL = "CDN_URL";
        public static readonly string CDN_FOLDER = "CDN_FOLDER";
        public static readonly string ADMINTOOL_DATETIME_FORMAT = "ADMINTOOL_DATETIME_FORMAT";
        public static readonly string ADMINTOOL_DATETIME_FORMAT_LONG = "ADMINTOOL_DATETIME_FORMAT_LONG";
        public static readonly string GUI_OPTION_HIDE_WARNING_AT_CP_LOGIN = "GUI_OPTION_HIDE_WARNING_AT_CP_LOGIN";
        public static readonly string CERTIFICATION_APS_PRODUCTION_FILE_NAME = "CERTIFICATION_APS_PRODUCTION_FILE_NAME";
        public static readonly string DEFAULT_RESET_PASSWORD = "DEFAULT_RESET_PASSWORD";
        public static readonly string PROTOCOL_MEDIA_URL = "PROTOCOL_MEDIA_URL";
        public static readonly string AMBIENT_RECORDING_TOTAL_FILE_NUMBER_FOR_EACH_ACCOUNT = "AMBIENT_RECORDING_TOTAL_FILE_NUMBER_FOR_EACH_ACCOUNT";
        public static readonly string AMBIENT_RECORDING_MAX_FILE_SIZE_FOR_EACH_FILE = "AMBIENT_RECORDING_MAX_FILE_SIZE_FOR_EACH_FILE";
        public static readonly string AMBIENT_RECORDING_MAX_SIZE_FOR_EACH_ACCOUNT = "AMBIENT_RECORDING_MAX_SIZE_FOR_EACH_ACCOUNT";
        public static readonly string AMBIENT_RECORDING_MAX_DURING_TIME = "AMBIENT_RECORDING_MAX_DURING_TIME";
        public static readonly string RELEASE_NOTES = "RELEASE_NOTES";
        public static readonly string DISPLAY_EXPIRING_SOON_BEFORE_X_DAYS = "DISPLAY_EXPIRING_SOON_BEFORE_X_DAYS";
        public static readonly string LINK_HOW_TO_ROOT_AN_ANDROID = "LINK_HOW_TO_ROOT_AN_ANDROID";
        public static readonly string KEY_DISPLAY_CPANEL_WELCOME_MESSAGE = "KEY_DISPLAY_CPANEL_WELCOME_MESSAGE";
        public static readonly string APPEAR_CAPTCHA_WHEN_COUNT_WRONG = "APPEAR_CAPTCHA_WHEN_COUNT_WRONG";
        public static readonly string VERSION_INFO = "VERSION_INFO";
    }
}
