<?xml version="1.0" encoding="utf-8"?><Database Name="VDEducation" Class="DataClasses3DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=103.10.44.30;Initial Catalog=VDEducation;Persist Security Info=True;User ID=VDCTeam" SettingsObjectName="Monitor2.Properties.Settings" SettingsPropertyName="VDEducationConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Class" Member="Classes">
    <Type Name="Class">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SchoolYearID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>