#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VDEducation")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSubject(Subject instance);
    partial void UpdateSubject(Subject instance);
    partial void DeleteSubject(Subject instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::Monitor2.Properties.Settings.Default.VDEducationConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Subject> Subjects
		{
			get
			{
				return this.GetTable<Subject>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subject")]
	public partial class Subject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Code;
		
		private string _Name;
		
		private System.Nullable<int> _ClassID;
		
		private string _Description;
		
		private System.Nullable<int> _TotalCredits;
		
		private System.Nullable<int> _PracticeCredit;
		
		private System.Nullable<int> _TheoryCredit;
		
		private System.Nullable<int> _LessionNumber;
		
		private System.Nullable<int> _FinalEvaluationPercent;
		
		private System.Nullable<int> _SemiFinalEvaluationPercent;
		
		private System.Nullable<int> _DiligencePercent;
		
		private System.Nullable<int> _SubjectTypeID;
		
		private string _SpecializeID;
		
		private string _Piority;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnClassIDChanging(System.Nullable<int> value);
    partial void OnClassIDChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnTotalCreditsChanging(System.Nullable<int> value);
    partial void OnTotalCreditsChanged();
    partial void OnPracticeCreditChanging(System.Nullable<int> value);
    partial void OnPracticeCreditChanged();
    partial void OnTheoryCreditChanging(System.Nullable<int> value);
    partial void OnTheoryCreditChanged();
    partial void OnLessionNumberChanging(System.Nullable<int> value);
    partial void OnLessionNumberChanged();
    partial void OnFinalEvaluationPercentChanging(System.Nullable<int> value);
    partial void OnFinalEvaluationPercentChanged();
    partial void OnSemiFinalEvaluationPercentChanging(System.Nullable<int> value);
    partial void OnSemiFinalEvaluationPercentChanged();
    partial void OnDiligencePercentChanging(System.Nullable<int> value);
    partial void OnDiligencePercentChanged();
    partial void OnSubjectTypeIDChanging(System.Nullable<int> value);
    partial void OnSubjectTypeIDChanged();
    partial void OnSpecializeIDChanging(string value);
    partial void OnSpecializeIDChanged();
    partial void OnPiorityChanging(string value);
    partial void OnPiorityChanged();
    #endregion
		
		public Subject()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="Int")]
		public System.Nullable<int> ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalCredits", DbType="Int")]
		public System.Nullable<int> TotalCredits
		{
			get
			{
				return this._TotalCredits;
			}
			set
			{
				if ((this._TotalCredits != value))
				{
					this.OnTotalCreditsChanging(value);
					this.SendPropertyChanging();
					this._TotalCredits = value;
					this.SendPropertyChanged("TotalCredits");
					this.OnTotalCreditsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PracticeCredit", DbType="Int")]
		public System.Nullable<int> PracticeCredit
		{
			get
			{
				return this._PracticeCredit;
			}
			set
			{
				if ((this._PracticeCredit != value))
				{
					this.OnPracticeCreditChanging(value);
					this.SendPropertyChanging();
					this._PracticeCredit = value;
					this.SendPropertyChanged("PracticeCredit");
					this.OnPracticeCreditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheoryCredit", DbType="Int")]
		public System.Nullable<int> TheoryCredit
		{
			get
			{
				return this._TheoryCredit;
			}
			set
			{
				if ((this._TheoryCredit != value))
				{
					this.OnTheoryCreditChanging(value);
					this.SendPropertyChanging();
					this._TheoryCredit = value;
					this.SendPropertyChanged("TheoryCredit");
					this.OnTheoryCreditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessionNumber", DbType="Int")]
		public System.Nullable<int> LessionNumber
		{
			get
			{
				return this._LessionNumber;
			}
			set
			{
				if ((this._LessionNumber != value))
				{
					this.OnLessionNumberChanging(value);
					this.SendPropertyChanging();
					this._LessionNumber = value;
					this.SendPropertyChanged("LessionNumber");
					this.OnLessionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalEvaluationPercent", DbType="Int")]
		public System.Nullable<int> FinalEvaluationPercent
		{
			get
			{
				return this._FinalEvaluationPercent;
			}
			set
			{
				if ((this._FinalEvaluationPercent != value))
				{
					this.OnFinalEvaluationPercentChanging(value);
					this.SendPropertyChanging();
					this._FinalEvaluationPercent = value;
					this.SendPropertyChanged("FinalEvaluationPercent");
					this.OnFinalEvaluationPercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SemiFinalEvaluationPercent", DbType="Int")]
		public System.Nullable<int> SemiFinalEvaluationPercent
		{
			get
			{
				return this._SemiFinalEvaluationPercent;
			}
			set
			{
				if ((this._SemiFinalEvaluationPercent != value))
				{
					this.OnSemiFinalEvaluationPercentChanging(value);
					this.SendPropertyChanging();
					this._SemiFinalEvaluationPercent = value;
					this.SendPropertyChanged("SemiFinalEvaluationPercent");
					this.OnSemiFinalEvaluationPercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiligencePercent", DbType="Int")]
		public System.Nullable<int> DiligencePercent
		{
			get
			{
				return this._DiligencePercent;
			}
			set
			{
				if ((this._DiligencePercent != value))
				{
					this.OnDiligencePercentChanging(value);
					this.SendPropertyChanging();
					this._DiligencePercent = value;
					this.SendPropertyChanged("DiligencePercent");
					this.OnDiligencePercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectTypeID", DbType="Int")]
		public System.Nullable<int> SubjectTypeID
		{
			get
			{
				return this._SubjectTypeID;
			}
			set
			{
				if ((this._SubjectTypeID != value))
				{
					this.OnSubjectTypeIDChanging(value);
					this.SendPropertyChanging();
					this._SubjectTypeID = value;
					this.SendPropertyChanged("SubjectTypeID");
					this.OnSubjectTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecializeID", CanBeNull=false)]
		public string SpecializeID
		{
			get
			{
				return this._SpecializeID;
			}
			set
			{
				if ((this._SpecializeID != value))
				{
					this.OnSpecializeIDChanging(value);
					this.SendPropertyChanging();
					this._SpecializeID = value;
					this.SendPropertyChanged("SpecializeID");
					this.OnSpecializeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piority", CanBeNull=false)]
		public string Piority
		{
			get
			{
				return this._Piority;
			}
			set
			{
				if ((this._Piority != value))
				{
					this.OnPiorityChanging(value);
					this.SendPropertyChanging();
					this._Piority = value;
					this.SendPropertyChanged("Piority");
					this.OnPiorityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
