using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using DevExpress.XtraGrid.Columns;
using ServiceCore.DataAccess;

namespace Monitor2
{
    public partial class UserControlTeacher : UserControl
    {
        public UserControlTeacher()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
        TeacherDAO teacherDAO = new TeacherDAO();

        private void panelControl1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void gridControl1_MouseDown(object sender, MouseEventArgs e)
        {
            GridHitInfo info = gridView1.CalcHitInfo(e.Location);
            if (info.InRowCell)
            {
                int row = info.RowHandle;
                GridColumn colum = info.Column;
                DataRow rowcolum = gridView1.GetDataRow(row);
                textEdit1.Text  = gridView1.GetRowCellValue(row, "ID").ToString();
                textEdit2.Text  = gridView1.GetRowCellValue(row, "FirstName").ToString();
                textEdit3.Text  = gridView1.GetRowCellValue(row, "LastName").ToString();
                textEdit4.Text  = gridView1.GetRowCellValue(row, "Gender").ToString();
                textEdit5.Text  = gridView1.GetRowCellValue(row, "Email").ToString();
                textEdit6.Text  = gridView1.GetRowCellValue(row, "BirthDate").ToString();
                textEdit7.Text  = gridView1.GetRowCellValue(row, "WorkUnit").ToString();
                textEdit8.Text  = gridView1.GetRowCellValue(row, "Graduating").ToString();
                textEdit9.Text  = gridView1.GetRowCellValue(row, "Diploma").ToString();
                textEdit10.Text = gridView1.GetRowCellValue(row, "BankAccountNumber").ToString();
                textEdit11.Text = gridView1.GetRowCellValue(row, "BankID").ToString();
                textEdit12.Text = gridView1.GetRowCellValue(row, "Description").ToString();
                textEdit13.Text = gridView1.GetRowCellValue(row, "SpecializeID").ToString();
                textEdit14.Text = gridView1.GetRowCellValue(row, "IDCardNumber").ToString();
                comboBox1.Text = gridView1.GetRowCellValue(row, "Khoa").ToString();
                //textEdit13.Text = gridView1.GetRowCellValue(row, "CareerID").ToString();
            }
        }
        //button them
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (teacherDAO.exedata("INSERT INTO Teacher (ID, FirstName, LastName,Gender, Email, BirthDate, WorkUnit, Graduating, Diploma, BankAccountNumber, BankID, Description,SpecializeID, IDCardNumber) VALUES ('" + textEdit1.Text + "',N'" + textEdit2.Text + "',N'" + textEdit3.Text + "','" + textEdit4.Text + "','" + textEdit5.Text + "','" + textEdit6.Text + "',N'" + textEdit7.Text + "',N'" + textEdit8.Text + "',N'" + textEdit9.Text + "','" + textEdit10.Text + "','" + textEdit11.Text + "',N'" + textEdit12.Text + "','" + textEdit13.Text + "','" + textEdit14.Text + "')") == true)
            {
                MessageBox.Show("Đã thêm dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể thêm dữ liệu");
            }
            sqlDataSource1.Fill();
        }

        //button sua
        private void simpleButton2_Click(object sender, EventArgs e)
        {
            if (teacherDAO.exedata("UPDATE Teacher SET FirstName = N'" + textEdit2.Text + "', LastName = N'" + textEdit3.Text + "',Gender ='" + textEdit4.Text + "' ,Email = '" + textEdit5.Text + "',BirthDate = '" + textEdit6.Text + "',WorkUnit = N'" + textEdit7.Text + "',Graduating =N'" + textEdit8.Text + "' ,Diploma =N'" + textEdit9.Text + "' ,BankAccountNumber ='" + textEdit10.Text + "' ,BankID ='" + textEdit11.Text + "',Description =N'" + textEdit12.Text + "',SpecializeID ='" + textEdit13.Text + "',IDCardNumber ='" + textEdit14.Text + "'  WHERE ID = '" + textEdit1.Text + "' ") == true)
            {
                MessageBox.Show("Đã Sửa dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể Sửa dữ liệu");
            }
            sqlDataSource1.Fill();
        }

        //button xoa
        private void simpleButton3_Click(object sender, EventArgs e)
        {
            if (teacherDAO.exedata("delete from Teacher where ID = '" + textEdit1.Text + "' ") == true)
            {
                MessageBox.Show("Đã Xóa dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể Xóa dữ liệu");
            }
            sqlDataSource1.Fill();
        }

        //button load
        private void simpleButton4_Click(object sender, EventArgs e)
        {
            textEdit1.Text = "";
            textEdit2.Text = "";
            textEdit3.Text = "";
            textEdit4.Text = "";
            textEdit5.Text = "";
            textEdit6.Text = "";
            textEdit7.Text = "";
            textEdit8.Text = "";
            textEdit9.Text = "";
            textEdit10.Text = "";
            textEdit11.Text = "";
            textEdit12.Text = "";
            textEdit13.Text = "";
            textEdit14.Text = "";
            comboBox1.Text = "";
            sqlDataSource1.Fill();
        }

        private void UserControlTeacher_Load(object sender, EventArgs e)
        {
            String sql = "Select ID, Name from Specialize";
            String display = "Name";
            String value = "ID";
            this.teacherDAO.loadCBB(comboBox1, sql, display, value);
            comboBox1.Text = "";
        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            this.textEdit13.Text = comboBox1.SelectedValue.ToString();
        }

        private void labelControl7_Click(object sender, EventArgs e)
        {

        }
    }
}
