using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using DevExpress.XtraGrid.Columns;
using System.Data.SqlClient;
using System.Configuration;
using ServiceCore.DataAccess;

namespace Monitor2
{
    public partial class UserControlBan : UserControl
    {
        KhoaDAO khoaDAO = new KhoaDAO();

        public UserControlBan()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();

            String sql = "Select ID, Name from Specialize";
            String display = "Name";
            String value = "ID";
            this.loadCBB(comboBox1, sql, display, value);
            comboBox1.Text = "";
        }

        private void gridView1_MouseDown(object sender, MouseEventArgs e)
        {
            GridHitInfo info = gridView1.CalcHitInfo(e.Location);
            if (info.InRowCell)
            {
                int row = info.RowHandle;
                GridColumn colum = info.Column;
                DataRow rowcolum = gridView1.GetDataRow(row);
                textEdit1.Text = gridView1.GetRowCellValue(row, "Name").ToString();
                comboBox1.Text = gridView1.GetRowCellValue(row, "Khoa").ToString();
                textEdit3.Text = gridView1.GetRowCellValue(row, "ID").ToString();
                textEdit4.Text = gridView1.GetRowCellValue(row, "SpecializeID").ToString();
            }
        }
       
  
        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            textEdit4.Text = comboBox1.SelectedValue.ToString();
        }

        public void loadCBB(ComboBox cmd, String sql, String display, String value)
        {
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["defaultConnection"].ToString());
            con.Open();
            DataSet dataSet;
            SqlDataAdapter adapter;
            SqlCommand sl = new SqlCommand(sql, con);
            adapter = new SqlDataAdapter(sl);
            dataSet = new DataSet();
            adapter.Fill(dataSet);
            cmd.DataSource = dataSet.Tables[0];
            cmd.DisplayMember = display;
            cmd.ValueMember = value;
            con.Close();
        }

        //button them
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (khoaDAO.exedata("INSERT INTO Department (Name,SpecializeID) VALUES (N'" + textEdit1.Text + "','" + textEdit4.Text + "')") == true)
            {
                MessageBox.Show("Đã thêm dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể thêm dữ liệu");
            }
            sqlDataSource1.Fill();
        }
        //button sua
        private void simpleButton2_Click(object sender, EventArgs e)
        {
            if (khoaDAO.exedata("UPDATE Department SET Name = N'" + textEdit1.Text + "', SpecializeID = '" + textEdit4.Text + "' WHERE ID = '" + textEdit3.Text + "' ") == true)
            {
                MessageBox.Show("Đã Sửa dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể Sửa dữ liệu");
            }
            sqlDataSource1.Fill();
        }
        //button xoa
        private void simpleButton3_Click(object sender, EventArgs e)
        {
            if (khoaDAO.exedata("delete from Department where ID = '" + textEdit3.Text + "' ") == true)
            {
                MessageBox.Show("Đã Xóa dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể Xóa dữ liệu");
            }
            sqlDataSource1.Fill();
        }
        //button load
        private void simpleButton4_Click(object sender, EventArgs e)
        {

            textEdit1.Text = "";
            comboBox1.Text = "";
            textEdit3.Text = "";
            textEdit4.Text = "";
            sqlDataSource1.Fill();
        }
    }
}
