using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;
using ExcelDataReader;

namespace Monitor2
{
    public partial class UserControlExcel : UserControl
    {
        //excel
        public UserControlExcel()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            OpenFileDialog dialog = new OpenFileDialog();
            dialog.Filter = "Excel Files|*.xlsx;*.xls;*.xlsm";
            if (dialog.ShowDialog() == DialogResult.Cancel)
                return;
            
            try {
                FileStream stream = new FileStream(dialog.FileName, FileMode.Open);
                IExcelDataReader excelDataReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                DataSet dataSet = excelDataReader.AsDataSet();
                DataClasses1DataContext conn = new DataClasses1DataContext();
                foreach (DataTable table in dataSet.Tables) {
                    foreach (DataRow dr in table.Rows) {
                        Student add = new Student()
                        {
                            ID = Convert.ToString(dr[0]),
                            FirstName = Convert.ToString(dr[1]),
                            LastName = Convert.ToString(dr[2]),
                            Email = Convert.ToString(dr[3]),
                            BirthDate = Convert.ToDateTime(dr[4]),
                            Gender = Convert.ToInt32(dr[5]),
                            ClassID = Convert.ToInt32(dr[6]),
                            Country = Convert.ToString(dr[7]),
                            Address = Convert.ToString(dr[8]),
                            PhoneNumber = Convert.ToString(dr[9]),
                            TrainingSystemID = Convert.ToInt32(dr[10]),
                        };
                        conn.Students.InsertOnSubmit(add);
                    }
                }
                conn.SubmitChanges();
                excelDataReader.Close();
                stream.Close();
                MessageBox.Show("Sucess");
                sqlDataSource1.Fill();
            }
            catch (Exception ex) {
                MessageBox.Show("Mã sinh Viên Không Được Trùng, Lỗi File Hoặc File Đang Mở");
            }
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            SaveFileDialog dialog = new SaveFileDialog();
            dialog.Filter = "Excel Files|*.xlsx;*.xls;*.xlsm";
            dialog.DefaultExt = "xls";
            if (dialog.ShowDialog() == DialogResult.OK)
            {
                this.gridView1.ExportToXls(dialog.FileName);
                MessageBox.Show("Sucess");
            }
        }
    }
}
