using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows.Forms;
using ServiceCore.DataAccess;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using DevExpress.XtraGrid.Columns;
using System.Data.SqlClient;
using System.Configuration;
using System.IO;
using ExcelDataReader;

namespace Monitor2
{
    public partial class UserControlStudent : UserControl
    {
        StudentDAO studentDao = new StudentDAO();
        public UserControlStudent()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
        //Button Load
        private void simpleButton4_Click(object sender, EventArgs e)
        {
            textEdit1.Text = "";
            textEdit2.Text = "";
            textEdit3.Text = "";
            textEdit4.Text = "";
            comboBox2.Text = "";
            textEdit6.Text = "";
            textEdit7.Text = "";
            textEdit8.Text = "";
            textEdit9.Text = "";
            textEdit10.Text = "";
            textEdit11.Text = "";
            comboBox1.Text = "";
            sqlDataSource1.Fill();

        }

        //Button Them 
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (studentDao.exedata("INSERT INTO Student (ID, FirstName, LastName, Email, BirthDate, Gender, ClassID, Country, Address, PhoneNumber, TrainingSystemID) VALUES ('" + textEdit1.Text + "',N'" + textEdit2.Text + "',N'" + textEdit3.Text + "','" + textEdit4.Text + "','" + textEdit10.Text + "','" + comboBox2.Text + "','" + textEdit6.Text + "',N'" + textEdit7.Text + "',N'" + textEdit8.Text + "','" + textEdit9.Text + "','" + textEdit11.Text + "')") == true)
            {
                MessageBox.Show("Đã thêm dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể thêm dữ liệu");
            }
            sqlDataSource1.Fill();
        }

        //Button Xoa
        private void simpleButton3_Click(object sender, EventArgs e)
        {
            if (studentDao.exedata("delete from Student where ID = '" + textEdit1.Text + "' ") == true)
            {
                MessageBox.Show("Đã Xóa dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể Xóa dữ liệu");
            }
            sqlDataSource1.Fill();
        }

        //Button Sua
        private void simpleButton2_Click(object sender, EventArgs e)
        {
            if (studentDao.exedata("UPDATE Student SET FirstName = N'" + textEdit2.Text + "', LastName = N'" + textEdit3.Text + "',Email = '" + textEdit4.Text + "',BirthDate = '" + textEdit10.Text + "',Gender ='" + comboBox2.Text + "' ,ClassID = '" + textEdit6.Text + "',Country =N'" + textEdit7.Text + "' ,Address =N'" + textEdit8.Text + "' ,PhoneNumber ='" + textEdit9.Text + "' ,TrainingSystemID ='" + textEdit11.Text + "'  WHERE ID = '" + textEdit1.Text + "' ") == true)
            {
                MessageBox.Show("Đã Sửa dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể Sửa dữ liệu");
            }
            sqlDataSource1.Fill();
        }


        private void gridControl1_MouseDown(object sender, MouseEventArgs e)
        {
        
            GridHitInfo info = gridView1.CalcHitInfo(e.Location);
            if (info.InRowCell)
            {
                int row = info.RowHandle;
                GridColumn colum = info.Column;
                DataRow rowcolum = gridView1.GetDataRow(row);
                textEdit1.Text = gridView1.GetRowCellValue(row, "ID").ToString();
                textEdit2.Text = gridView1.GetRowCellValue(row, "FirstName").ToString();
                textEdit3.Text = gridView1.GetRowCellValue(row, "LastName").ToString();
                textEdit4.Text = gridView1.GetRowCellValue(row, "Email").ToString();
                comboBox2.Text = gridView1.GetRowCellValue(row, "Gender").ToString();
                textEdit6.Text = gridView1.GetRowCellValue(row, "ClassID").ToString();
                textEdit7.Text = gridView1.GetRowCellValue(row, "Country").ToString();
                textEdit8.Text = gridView1.GetRowCellValue(row, "Address").ToString();
                textEdit9.Text = gridView1.GetRowCellValue(row, "PhoneNumber").ToString();
                textEdit10.Text = gridView1.GetRowCellValue(row, "BirthDate").ToString();
                textEdit11.Text = gridView1.GetRowCellValue(row, "TrainingSystemID").ToString();
                comboBox1.Text = gridView1.GetRowCellValue(row, "Code").ToString();


            }
        }
        public void loadCBB( ComboBox cmd, String sql, String display, String value) {
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["defaultConnection"].ToString());
            con.Open();
            DataSet dataSet;
            SqlDataAdapter adapter;
            SqlCommand sl = new SqlCommand(sql,con);
            adapter = new SqlDataAdapter(sl);
            dataSet = new DataSet();
            adapter.Fill(dataSet);
            cmd.DataSource = dataSet.Tables[0];
            cmd.DisplayMember = display;
            cmd.ValueMember = value;
            con.Close();
        }

        private void UserControlStudent_Load(object sender, EventArgs e)
        {
            String sql = "Select ID, Code from Class";
            String display = "Code";
            String value = "ID";
            this.loadCBB(comboBox1, sql, display, value);
            comboBox1.Text = "";

        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            this.textEdit6.Text = comboBox1.SelectedValue.ToString();
            
        }

        private void textEdit6_EditValueChanged(object sender, EventArgs e)
        {
        }

        private void labelControl9_Click(object sender, EventArgs e)
        {

        }
        //export
        private void simpleButton6_Click(object sender, EventArgs e)
        {
            SaveFileDialog dialog = new SaveFileDialog();
            dialog.Filter = "Excel Files|*.xlsx;*.xls;*.xlsm";
            dialog.DefaultExt = "xls";
            if (dialog.ShowDialog() == DialogResult.OK)
            {
                this.gridView1.ExportToXls(dialog.FileName);
                MessageBox.Show("Sucess");
            }
        }

        //import
        private void simpleButton5_Click(object sender, EventArgs e)
        {
            OpenFileDialog dialog = new OpenFileDialog();
            dialog.Filter = "Excel Files|*.xlsx;*.xls;*.xlsm";
            if (dialog.ShowDialog() == DialogResult.Cancel)
                return;
            
                try
            {
                FileStream stream = new FileStream(dialog.FileName, FileMode.Open);
                IExcelDataReader excelDataReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                DataSet dataSet = excelDataReader.AsDataSet();
                DataClasses1DataContext conn = new DataClasses1DataContext();
                foreach (DataTable table in dataSet.Tables)
                {
                    foreach (DataRow dr in table.Rows)
                    {
                        Student add = new Student()
                        {
                            ID = Convert.ToString(dr[0]),
                            FirstName = Convert.ToString(dr[1]),
                            LastName = Convert.ToString(dr[2]),
                            Email = Convert.ToString(dr[3]),
                            BirthDate = Convert.ToDateTime(dr[4]),
                            Gender = Convert.ToInt32(dr[5]),
                            ClassID = Convert.ToInt32(dr[6]),
                            Country = Convert.ToString(dr[7]),
                            Address = Convert.ToString(dr[8]),
                            PhoneNumber = Convert.ToString(dr[9]),
                            TrainingSystemID = Convert.ToInt32(dr[10])
                        };
                        conn.Students.InsertOnSubmit(add);
                    }
                }
                conn.SubmitChanges();
                excelDataReader.Close();
                stream.Close();
                MessageBox.Show("Sucess");
                sqlDataSource1.Fill();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Mã sinh Viên Không Được Trùng, Lỗi File Hoặc File Đang Mở");
            }
        }
    }
    
}
