using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using ServiceCore.DataAccess;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using DevExpress.XtraGrid.Columns;

namespace Monitor2
{
    public partial class UserControlKhoa : UserControl
    {
        KhoaDAO khoaDAO = new KhoaDAO();
        public UserControlKhoa()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
         //Button Them
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (khoaDAO.exedata("INSERT INTO Specialize (Name,Description) VALUES (N'" + textEdit1.Text + "',N'" + textEdit3.Text + "')") == true)
            {
                MessageBox.Show("Đã thêm dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể thêm dữ liệu");
            }
            sqlDataSource1.Fill();
        }
        //Button Sua
        private void simpleButton2_Click(object sender, EventArgs e)
        {
            if (khoaDAO.exedata("UPDATE Specialize SET Name = N'" + textEdit1.Text + "', Description = N'"+ textEdit3.Text + "' WHERE ID = '" + textEdit2.Text + "' ") == true)
            {
                MessageBox.Show("Đã Sửa dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể Sửa dữ liệu");
            }
            sqlDataSource1.Fill();
        }

        //Button xoa
        private void simpleButton3_Click(object sender, EventArgs e)
        {
            if (khoaDAO.exedata("delete from Specialize where ID = '" + textEdit2.Text + "' ") == true)
            {
                MessageBox.Show("Đã Xóa dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể Xóa dữ liệu");
            }
            sqlDataSource1.Fill();
        }

        //Button Load
        private void simpleButton4_Click(object sender, EventArgs e)
        {

            textEdit1.Text = "";
            textEdit2.Text = "";
            textEdit3.Text = "";
            sqlDataSource1.Fill();
        }

        private void gridControl1_MouseDown(object sender, MouseEventArgs e)
        {
            GridHitInfo info = gridView1.CalcHitInfo(e.Location);
            if (info.InRowCell)
            {
                int row = info.RowHandle;
                GridColumn colum = info.Column;
                DataRow rowcolum = gridView1.GetDataRow(row);
                textEdit1.Text = gridView1.GetRowCellValue(row, "Name").ToString();
                textEdit2.Text = gridView1.GetRowCellValue(row, "ID").ToString();
                textEdit3.Text = gridView1.GetRowCellValue(row, "Description").ToString();

            }
        }
    }
}
