using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;
using ExcelDataReader;

namespace Monitor2
{
    public partial class UserControlImportSubject : UserControl
    {
        public UserControlImportSubject()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            OpenFileDialog dialog = new OpenFileDialog();
            dialog.Filter = "Excel Files|*.xlsx;*.xls;*.xlsm";
            if (dialog.ShowDialog() == DialogResult.OK)
            {
                FileStream stream = new FileStream(dialog.FileName, FileMode.Open);
                IExcelDataReader excelDataReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                DataSet dataSet = excelDataReader.AsDataSet();
                DataClasses2DataContext conn = new DataClasses2DataContext();
                try
                {

                    foreach (DataTable table in dataSet.Tables)
                    {
                        foreach (DataRow dr in table.Rows)
                        {
                            Subject add = new Subject()
                            {
                                //ID = Convert.ToInt32(dr[0]),
                                Code = Convert.ToString(dr[0]),
                                Name = Convert.ToString(dr[1]),
                                //ClassID = Convert.ToInt32(dr[2]),
                                Description = Convert.ToString(dr[2]),
                                TotalCredits = Convert.ToInt32(dr[3]),
                                PracticeCredit = Convert.ToInt32(dr[4]),
                                TheoryCredit = Convert.ToInt32(dr[5]),
                                LessionNumber = Convert.ToInt32(dr[6]),
                                FinalEvaluationPercent = Convert.ToInt32(dr[7]),
                                SemiFinalEvaluationPercent = Convert.ToInt32(dr[8]),
                                DiligencePercent = Convert.ToInt32(dr[9]),
                                SubjectTypeID = Convert.ToInt32(dr[10]),
                            };
                            conn.Subjects.InsertOnSubmit(add);
                        }
                    }
                    conn.SubmitChanges();
                    excelDataReader.Close();
                    stream.Close();
                    MessageBox.Show("Sucess");
                    sqlDataSource1.Fill();
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Error");
                }
            }
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            SaveFileDialog dialog = new SaveFileDialog();
            dialog.Filter = "Excel Files|*.xlsx;*.xls;*.xlsm";
            dialog.DefaultExt = "xls";
            if (dialog.ShowDialog() == DialogResult.OK)
            {
                this.gridView1.ExportToXls(dialog.FileName);
                MessageBox.Show("Sucess");
            }
        }
    }
}
