using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using DevExpress.XtraGrid.Columns;
using ServiceCore.DataAccess;
using System.IO;
using ExcelDataReader;

namespace Monitor2
{
    public partial class UserControlSubject : UserControl
    {
        public UserControlSubject()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
        SubjectDAO subjectDAO = new SubjectDAO();
        private void gridControl1_MouseDown(object sender, MouseEventArgs e)
        {
            GridHitInfo info = gridView1.CalcHitInfo(e.Location);
            if (info.InRowCell)
            {
                int row = info.RowHandle;
                GridColumn colum = info.Column;
                DataRow rowcolum = gridView1.GetDataRow(row);
                textEdit1.Text = gridView1.GetRowCellValue(row, "ID").ToString();
                textEdit2.Text = gridView1.GetRowCellValue(row, "Code").ToString();
                textEdit3.Text = gridView1.GetRowCellValue(row, "Name").ToString();
                comboBox1.Text = gridView1.GetRowCellValue(row, "Khoa").ToString();
                textEdit5.Text = gridView1.GetRowCellValue(row, "Description").ToString();
                textEdit6.Text = gridView1.GetRowCellValue(row, "TotalCredits").ToString();
                textEdit7.Text = gridView1.GetRowCellValue(row, "PracticeCredit").ToString();
                textEdit8.Text = gridView1.GetRowCellValue(row, "TheoryCredit").ToString();
                textEdit9.Text = gridView1.GetRowCellValue(row, "LessionNumber").ToString();
                textEdit10.Text = gridView1.GetRowCellValue(row, "FinalEvaluationPercent").ToString();
                textEdit11.Text = gridView1.GetRowCellValue(row, "SemiFinalEvaluationPercent").ToString();
                textEdit12.Text = gridView1.GetRowCellValue(row, "DiligencePercent").ToString();
                textEdit13.Text = gridView1.GetRowCellValue(row, "SubjectTypeID").ToString();
                textEdit14.Text = gridView1.GetRowCellValue(row, "SpecializeID").ToString();
                textEdit4.Text = gridView1.GetRowCellValue(row, "Piority").ToString();
                String pio = gridView1.GetRowCellValue(row, "Piority").ToString();
                if (pio == "0")
                {
                    comboBox2.Text = "Môn Cơ Sở";
                }
                if (pio == "1")
                {
                    comboBox2.Text = "Môn Cơ Bản";
                }
                if (pio == "2")
                {
                    comboBox2.Text = "Môn Nâng Cao";
                }
                //comboBox2.Text = gridView1.GetRowCellValue(row, "Piority").ToString();
                
            }
        }

        private void textEdit6_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void textEdit14_EditValueChanged(object sender, EventArgs e)
        {

        }

        //Button them
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (subjectDAO.exedata("INSERT INTO Subject (Code, Name, Description, TotalCredits, PracticeCredit, TheoryCredit, LessionNumber, FinalEvaluationPercent, SemiFinalEvaluationPercent, DiligencePercent,SubjectTypeID,SpecializeID,Piority) VALUES (N'" + textEdit2.Text + "',N'" + textEdit3.Text + "',N'" + textEdit5.Text + "','" + textEdit6.Text + "','" + textEdit7.Text + "','" + textEdit8.Text + "','" + textEdit9.Text + "','" + textEdit10.Text + "','" + textEdit11.Text + "','" + textEdit12.Text + "','" + textEdit13.Text + "','" + textEdit14.Text + "','" + textEdit4.Text + "')") == true)
            {
                MessageBox.Show("Đã thêm dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể thêm dữ liệu");
            }
            sqlDataSource1.Fill();
        }

        //button sua
        private void simpleButton2_Click(object sender, EventArgs e)
        {
            if (subjectDAO.exedata("UPDATE Subject SET Code = N'" + textEdit2.Text + "', Name = N'" + textEdit3.Text + "',Description = N'" + textEdit5.Text + "',TotalCredits = '" + textEdit6.Text + "',PracticeCredit = '" + textEdit7.Text + "',TheoryCredit ='" + textEdit8.Text + "' ,LessionNumber ='" + textEdit9.Text + "' ,FinalEvaluationPercent ='" + textEdit10.Text + "' ,SemiFinalEvaluationPercent ='" + textEdit11.Text + "',DiligencePercent ='" + textEdit12.Text + "',SubjectTypeID ='" + textEdit13.Text + "',SpecializeID ='" + textEdit14.Text + "',Piority ='" + textEdit4.Text + "'  WHERE ID = '" + textEdit1.Text + "' ") == true)
            {
                MessageBox.Show("Đã Sửa dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể Sửa dữ liệu");
            }
            sqlDataSource1.Fill();
        }

        //Button xoa
        private void simpleButton3_Click(object sender, EventArgs e)
        {
            if (subjectDAO.exedata("delete from Subject where ID = '" + textEdit1.Text + "' ") == true)
            {
                MessageBox.Show("Đã Xóa dữ liệu");
            }
            else
            {
                MessageBox.Show("Không thể Xóa dữ liệu");
            }
            sqlDataSource1.Fill();
        }

        //Button Load
        private void simpleButton4_Click(object sender, EventArgs e)
        {
            textEdit1.Text = "";
            textEdit2.Text = "";
            textEdit3.Text = "";
            textEdit4.Text = "";
            comboBox1.Text = "";
            comboBox2.Text = "";
            textEdit5.Text = "";
            textEdit6.Text = "";
            textEdit7.Text = "";
            textEdit8.Text = "";
            textEdit9.Text = "";
            textEdit10.Text = "";
            textEdit11.Text = "";
            textEdit12.Text = "";
            textEdit13.Text = "";
            textEdit14.Text = "";
            sqlDataSource1.Fill();
        }

        private void textEdit10_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            this.textEdit14.Text = comboBox1.SelectedValue.ToString();
        }

        private void UserControlSubject_Load(object sender, EventArgs e)
        {
            String sql = "Select ID, Name from Specialize";
            String display = "Name";
            String value = "ID";
            this.subjectDAO.loadCBB(comboBox1, sql, display, value);
            comboBox1.Text = "";

            comboBox2.DisplayMember = "Text";
            comboBox2.ValueMember = "Value";

            var items = new[] {
                new { Text = "Môn Cơ Sở", Value = "0" },
                new { Text = "Môn Cơ Bản", Value = "1" },
                new { Text = "Môn Nâng Cao", Value = "2" },
               
            };

            comboBox2.DataSource = items;
        }

        private void textEdit8_EditValueChanged(object sender, EventArgs e)
        {

        }
        //import
        private void simpleButton5_Click(object sender, EventArgs e)
        {
            OpenFileDialog dialog = new OpenFileDialog();
            dialog.Filter = "Excel Files|*.xlsx;*.xls;*.xlsm";
            if (dialog.ShowDialog() == DialogResult.OK)
            {
                FileStream stream = new FileStream(dialog.FileName, FileMode.Open);
                IExcelDataReader excelDataReader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                DataSet dataSet = excelDataReader.AsDataSet();
                DataClasses2DataContext conn = new DataClasses2DataContext();
                try
                {

                    foreach (DataTable table in dataSet.Tables)
                    {
                        foreach (DataRow dr in table.Rows)
                        {
                            Subject add = new Subject()
                            {
                                //ID = Convert.ToInt32(dr[0]),
                                Code = Convert.ToString(dr[0]),
                                Name = Convert.ToString(dr[1]),
                                //ClassID = Convert.ToInt32(dr[2]),
                                Description = Convert.ToString(dr[2]),
                                TotalCredits = Convert.ToInt32(dr[3]),
                                PracticeCredit = Convert.ToInt32(dr[4]),
                                TheoryCredit = Convert.ToInt32(dr[5]),
                                LessionNumber = Convert.ToInt32(dr[6]),
                                FinalEvaluationPercent = Convert.ToInt32(dr[7]),
                                SemiFinalEvaluationPercent = Convert.ToInt32(dr[8]),
                                DiligencePercent = Convert.ToInt32(dr[9]),
                                SubjectTypeID = Convert.ToInt32(dr[10]),
                                SpecializeID = Convert.ToString(dr[11]),
                                Piority = Convert.ToString(dr[12])
                            };
                            conn.Subjects.InsertOnSubmit(add);
                        }
                    }
                    conn.SubmitChanges();
                    excelDataReader.Close();
                    stream.Close();
                    MessageBox.Show("Sucess");
                    sqlDataSource1.Fill();
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Error");
                }
            }
        }
        //export
        private void simpleButton6_Click(object sender, EventArgs e)
        {
            SaveFileDialog dialog = new SaveFileDialog();
            dialog.Filter = "Excel Files|*.xlsx;*.xls;*.xlsm";
            dialog.DefaultExt = "xls";
            if (dialog.ShowDialog() == DialogResult.OK)
            {
                this.gridView1.ExportToXls(dialog.FileName);
                MessageBox.Show("Sucess");
            }
        }

        private void textEdit14_EditValueChanged_1(object sender, EventArgs e)
        {

        }

        private void comboBox2_SelectedIndexChanged(object sender, EventArgs e)
        {
            textEdit4.Text = comboBox2.SelectedValue.ToString();
        }
    }
}
