using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using ServiceCore.DataAccess;
using DevExpress.DataAccess.Sql;
using VD.Datalayer.DataObject;
using VD.Utility;
using ServiceCore.Models.Subject;
using System.Data.SqlClient;
using System.Configuration;

namespace Monitor2
{
    public partial class UserControlClassDetails : UserControl
    {
        ClassDAO classDao = new ClassDAO();
        CCoreDao dao = new CCoreDao();
        private GenerateData Render = new GenerateData();
        public List<SubjectModel> aa;
        public UserControlClassDetails()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource


            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
          
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            ClassTerm fclass = new ClassTerm();
            fclass.Show();
        }

        private void UserControlClassDetails_Load(object sender, EventArgs e)
        {
                String sql = "Select ID, Name from Class";
                String display = "Name";
                String value = "ID";
                classDao.loadCBB(comboBox1, sql, display, value);
            comboBox1.Text = "";
            textEdit1.Text = "";
            
        }
          

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            this.textEdit1.Text = comboBox1.SelectedValue.ToString();
            try
            {
                int idd = Int32.Parse(textEdit1.Text);
                aa = GetClassSubjectLearn(idd.ToString(), "LEARNED");
                gridControl1.DataSource = aa;
            }
            catch (Exception ex)
            {
                
            }
            
          
               

        }

        public List<SubjectModel> GetClassSubjectLearn(String Classid, String status)
        { 
            string xml = Render.GenerateXmlFromObject<object>(null, new
            {
                ClassID = Classid
            }, "1006", status, "13");
            var ds = dao.GetContextData(xml);
            var resp = Render.ResponseMultiObject<SubjectModel>(ds.Tables[0]).ToList();
            return resp;
        }

        private void gridControl1_Load(object sender, EventArgs e)
        {
           
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }
    }
}
